src/currencyservice/package-lock.json
src/currencyservice/package.json
src/paymentservice/package-lock.json
src/paymentservice/package.json
src/recommendationservice/requirements.txt

updated vulnerable packages. I launched the app and it seems to work with no problems @simonz130 are there any automated tests that would catch any hard to spot issues?

Fix vulnerabilities

---

terraform/install.sh

Display useful information when deploy is complete
Let me know if there's anything that would be useful to add

Success message

---

README.md

A bunch of suggested minor edits to the README.md file.These attempt to regularize constructions and use more idiomatic language.

Suggestions for README.md

---

loadgenerator/loadgenerator-tool
src/frontend/templates/footer.html

- Update the Sandbox repo link in home page footer of the Hipster Shop
- Minor fixes to loadgen text

Update the sandbox repo link in page footer

---

src/emailservice/Dockerfile
src/loadgenerator/Dockerfile
src/productcatalogservice/Gopkg.lock
src/productcatalogservice/Gopkg.toml
src/productcatalogservice/server.go
src/recommendationservice/Dockerfile

Upgrade hipstershop to the latest version of opencensus exporter

---

docs/README.md

Added creation of Analysis Reports to documentation

---

docs/index.html

Addresses this issue: https://github.com/GoogleCloudPlatform/stackdriver-sandbox/issues/45

Added User Guide to webpage

---

CONTRIBUTING.md
loadgenerator/loadgen
terraform/install.sh

Addresses #21, and corrects a very small error in the contributing docs.

[refactor] Rename loadgenerator-tool to loadgen

---

terraform/monitoring/00_provider.tf
terraform/monitoring/02_dashboards.tf

#WHAT: Terraform support to create example dashboard for User Experience, contains metrics that are relevant to user interaction with the application
#WHY: We want to provide dashboard that reveals metrics about the demo application as whole
#HOW: Additional terraform config file created alongside initial provisioning terraform

User experience dashboard

---

docs/README.md

This solves issue 134: https://github.com/GoogleCloudPlatform/stackdriver-sandbox/issues/134.

Added documentation of destroy.sh

---

CONTRIBUTING.md

Fixes #163.
Adds instructions to CONTRIBUTING.md for building and running individual services using Docker locally. Addresses a potential issue if the local environment isn't set up to authenticate for GCP.

docs: instructions for building and running using docker locally

---

src/emailservice/email_server.py
src/emailservice/requirements.in
src/emailservice/requirements.txt
src/recommendationservice/recommendation_server.py
src/recommendationservice/requirements.in
src/recommendationservice/requirements.txt

This PR addresses the Python side of https://github.com/GoogleCloudPlatform/stackdriver-sandbox/pull/178

Update Python OpenCensus

---

terraform/monitoring/02_dashboards.tf
terraform/monitoring/dashboards/frontend_dashboard.json
terraform/monitoring/dashboards/userexp_dashboard.json
terraform/monitoring/variables.tf
tests/monitoring_integration_test.py

#WHAT: Frontend Service Dashboards using Istoi
#WHY: We want to use Istio to demonstrate the four golden signals for the frontend service
#HOW: Terraform resource
#TESTING: Integration test for resource creation passes.
Closes #61

frontend dashboards

---

src/frontend/main.go

Resolves issue #229 for this release - Restores the OpenCensus automatic HTTP handler wrapper that collects metrics. This is needed for the User Experience Dashboard, otherwise there is an "error trying to retrieve data." I removed this in #183 with the intention of using OpenTelemetry metrics (othttp) instead, but the metrics exporter isn't ready yet.
Tested manually, the user dashboard should now display info:
And OpenCensus http metrics should be visible from Monitoring > Metrics Explorer:

restore ochttp metrics for userexp dashboard

---

terraform/install.sh

#WHAT: Runs the terraform for monitoring examples as part of the provisioning install.sh script
#WHY: We want customers to be able to have monitoring examples automatically created during Sandbox creation
#HOW: Added it to the install script since this is the easiest way to retrieve the external IP and project ID for creating the monitoring examples. We will want to move this to be terraform in the future.
#TESTING: None :( did a manual test to verify it works correctly
Closes #231

add monitoring as part of installation

---

terraform/install.sh

Set current environment to use the property of selected project.

set current project

---

src/recommendationservice/Dockerfile
src/recommendationservice/client.py
src/recommendationservice/recommendation_server.py
src/recommendationservice/requirements.in
src/recommendationservice/requirements.txt

Resolves #291 , subtask of #132 
Clicking on any product in HipsterShop shows a row of 4 recommendations at the bottom; the corresponding trace in GCP Trace Console looks like this (g.co/agent should be opentelemetry, not opencensus):

OpenTelemetry Tracing for Recommendation Service

---

src/paymentservice/index.js
src/paymentservice/package-lock.json
src/paymentservice/package.json
src/paymentservice/server.js
src/paymentservice/tracer.js

Resolves #323 and subtask of #132 
Payment is only called by Checkout Service. It calls `Charge()`, i.e. to "charge the credit card." You should see both the client and server side calls to Charge in Trace console:
Also removes @google-cloud/trace-agent because it's not needed anymore :) and it causes the PROJECT_ID NOT FOUND errors.

Add OpenTelemetry Tracing for Payment service

---

src/checkoutservice/main.go
src/currencyservice/package-lock.json
src/currencyservice/package.json
src/currencyservice/server.js

Resolves #311, subtask of #132 
Currency service acts as a server to Frontend (GetSupportedCurrencies() and Convert()) and the Checkout service in PlaceOrder (Convert()).
To manually test this branch, you can see it from (1) home page or (2) at checkout.
Frontend uses `GetSuportedCurrencies` to show the menu of currencies; the corresponding trace should show both `client-hipstershop.currencyService` (which comes from frontend) and `grpc.hipstershop.CurrencyService` (which comes from CurrencyService itself and means the context was properly propagated through grpc). 
AND It should also show the HTTP call to the ECB website 💶  🤑  💸  💵 
For Checkout, you need to add an item to the cart and click check out. Checkout.PlaceOrder() dispatches 6 calls to the other services, one of which is the …

OpenTelemetry Tracing for Currency Service

---

terraform/02_project.tf
terraform/03_gke_cluster.tf
terraform/destroy.sh
terraform/install.sh

Fixes #334 
Change "stackdriver" to "cloud ops" in install.sh, destroy.sh and .tf files.
@nicklin37 will modify what is in istio and monitoring module.

sandbox rebranding

---

.github/workflows/e2e.yml
.github/workflows/e2e_scripts/clean.sh
.github/workflows/e2e_scripts/cleanup_monitoring.py
.github/workflows/e2e_scripts/requirements.txt
.github/workflows/install-dependencies.sh
tests/monitoring_integration_test.py

#WHAT: Integrates the monitoring integration tests into the e2e tests of the CI pipeline.
- Provisions monitoring examples with provisioning of the sandbox
- Checks for successful provisioning
- cleans up all provisioned monitoring resources using the API
#WHY: We want to automatically run the monitoring integration tests.
#HOW: Added Python script to deal with resource deletion, Python script for testing linked to the CI.
#TESTING: Manual test of deletion script works and same with monitoring integration test.

Monitoring Integration Test added to E2E CI

---

tests/requirements.txt

Need this package to retrieve the zone for the monitoring integration tests.

added google api client to packages for integration tests

---

tests/provisioning/README.md

Make user run tests on Cloud Shell to easy fix the credential issue.
Fixes #375.

Local test

---

.github/workflows/e2e.yml
.github/workflows/e2e_scripts/clean.sh
.github/workflows/e2e_scripts/cleanup_monitoring.py
loadgenerator/loadgen
terraform/install.sh
terraform/monitoring/05_alerting_policies.tf
terraform/monitoring/istio_service_setup.py
tests/monitoring_integration_test.py

This will cleanup the monitoring before the cluster is destroyed and the Istio services are lost.

reorder e2e cleanup to clean monitoring first

---

cloud-shell/Dockerfile

Fixes issue #400 and unblocks @nicklin37's work
Custom Cloud Shell Image installs Terraform v0.13.1.

Update terraform version

---

README.md

Updated OpenCensus mentions to OpenTelemetry since this is what we use now for instrumenting the app with traces.

Update readme.md for tracing

---

cloud-shell/Dockerfile
sre-recipes/recipes/currencies_recipe/currencies_recipe.py

Fixes an issue where kubectl will return localhost errors because it does not have authentication for the cluster.
Fixes #445

auth cluster for CLI & added to PATH

---

kubernetes-manifests/recommendationservice.yaml

fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/15

remove probes from recommendation service

---

terraform/install.sh

Resolves https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/443. Highlight the message to internal users about the /untrusted/demos/cloud-ops-sandboxes folder

Highlight Googler message

---

CODEOWNERS

Add member to CODEOWNERS

---

website/css/main.css
website/index.html

Added a warning to the main web page that clicking the button will terminate Cloud Shell session.
Removed extra commits from bad branch creation in PR #566 (disregard that PR).
Fixes #550

Warn clicking will terminate Cloud Shell sessions

---

src/frontend/static/css/styles.css
src/frontend/templates/footer.html
src/frontend/templates/header.html
src/frontend/templates/home.html
src/frontend/templates/product.html

The frontend microservice templates are modified to show product rating and allowing posting a new rating. Changes are made in the home page and the product page. In both page a rating of the product(s) is displayed in the form of the gauge of 5 stars filled proportionally to the value of the rating. The value of the rating is hardcoded to be 3.5 for mocking. In addition, the product page also shows a form to vote for the product's rating that allows selecting rating from 1 to 5. Once the "Vote" button is pressed, the form becomes invisible.
The integration with rating microservice will be added after the UI is agreed and merged.

Implement a mocked UI for product rating

---

.github/workflows/e2e-latest.yml
terraform/ratingservice/configure_rating_db.sh
terraform/ratingservice/main.tf
terraform/ratingservice/setup_app_engine.sh
tests/ratingservice/main_test.py

Implement clever verification of the established connection using Cloud SQL Proxy.
Fix #576

Implement tech debt and fix #576

---

src/ratingservice/main.py
terraform/ratingservice/README.md
terraform/ratingservice/main.tf
tests/ratingservice/main_test.py

Follow the Google [guidelines](https://cloud.google.com/apis/design/custom_methods) for custom method endpoint definition for the "recollect" API.

make recollect API follow the custom method guidelines

---

terraform/istio/install_istio.sh

ci: istio 1.8 requires installation confirmation

---

terraform/ratingservice/configure_rating_db.sh

reduce the number of populated votes for each rating to 1 in order to better visualize rating change.
fix #603.

make number of populated votes = 1

---

sre-recipes/recipe.py
sre-recipes/sandboxctl

Added describe and supported functions + separated  get project id for reuse

Add sandboxctl describe #648

---

docs/tutorial.md
sre-recipes/recipes/currencies_recipe/currencies_recipe.py

docs: warn users about latency with recipe0

---

renovate.json

This may help us keep node dependencies up to date
b/182378788

added lock maintainence to rennovate.json

---

website/content/en/docs/User Guide/Explore your project in GCP/_index.md

Issue #540

---

website/content/en/docs/User Guide/Destroying your cluster/_index.md
website/content/en/docs/User Guide/Explore your project in GCP/_index.md
website/content/en/docs/User Guide/Learn Ops Management/cloud_monitoring.md
website/content/en/docs/getting_started.md

Alignment between old Readme and User Guide website

Readmes alignment

---

src/emailservice/requirements.txt
src/recommendationservice/requirements.txt

Trying something. 
Also I noticed our renovate-bot PRs are updating `requirements.txt` rather than `.in`, so those two files are out of sync. I'm assuming requirements.in wont overwrite .txt for the time being. 😬

chore: update python rsa dep

---

.github/auto-label.yaml

I have a plan to implement the config schema check upon config file retrieval in auto-label bot.
I want to remove the wrong field (it's not in the schema definition) before deploying the change.

chore: update auto-label.yaml

---

sre-recipes/sandboxctl

* Lint
* Remove unused module
* Use format string

nit: Lint and fix sandboxctl to meet Python3 standard

---

Makefile
kubernetes-manifests/frontend.yaml

Fix shellscript lines in Makefile

---

cloud-shell/Dockerfile
terraform/install.sh

updates terraform to the latest version
Fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/755

update terraform to v1.0.0

---

terraform/install.sh

changing typo KBE to GKE

---

sre-recipes/sandboxctl

In the output of describe there was unneeded " in the beginning of each line.

fix(describe): Remove unnecessary " from output 

---

kubernetes-manifests/frontend.yaml

Increased mem+cpu based on resources needed for loadgen of 100&150 users.
Only changed  kubernetes-manifests/frontend.yaml rest of the changes are from deploy.

fix: Increase frontend pod resources 

---

renovate.json
sre-recipes/sandboxctl

fixes #883
We do not make use of this feature

chore: Remove dependency dashboard

---

terraform/01_provider.tf
terraform/monitoring/00_provider.tf

chore: pin terraform provider version

---

cloud-shell/Dockerfile
src/ratingservice/requirements.txt
terraform/ratingservice/04_appengine.tf

Update dependencies in cloud-shell and rating service to fix python runtime errors.

chore: update dependencies

---

cmd/install.sh

Review and modify the [existing][] install.sh Bash script to implement `create` and `delete` operations that provision and destroy Sandbox artifacts.
The revised implementation support the new Terraform configuration that provisioning Sandbox artifacts based on the application configuration.
[existing]: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/f0d95dc95a19404ff40bb97d85553b9d17ef1acd/terraform/install.sh

feat: implement revised create and delete Sandbox operations using Bash script

---

.github/PULL_REQUEST_TEMPLATE.md

chore(fix): Fix broken link to CONTRIBUTING.md

---

provisioning/configurations/online-boutique/dashboards/log_based_metric_dashboard.json
provisioning/install.sh
provisioning/terraform/cloudops.tf
provisioning/terraform/monitoring/alerts.tf
provisioning/terraform/monitoring/dashboards.tf
provisioning/terraform/monitoring/notification_channels.tf
provisioning/terraform/monitoring/slo_service/main.tf
provisioning/terraform/monitoring/slo_services.tf
provisioning/terraform/monitoring/variables.tf
provisioning/terraform/online-boutique.tf

Provisions SLOs and SLO alerts for Online Boutique services when ASM is installed.
Creates a custom dashboard to monitor log-based metrics.

fix: Add missing Cloud Ops artifact

---

README.md
docs/README.md
docs/walkthrough.md
provisioning/kustomize/online-boutique/kustomization.yaml
provisioning/sandboxctl
provisioning/terraform/providers.tf

The version 0.9.3 includes the following fixes:
* Refactoring documentation to address broken links
* Fixing incorrectly advertised commands in the walkthrough and the README files including `gcloud auth` and `sandboxctl create` commands
* Hide the status badge from the README file at the root
* Remove the top boundary on the terraform version to allow terraform versions ≥ 1.6.0
* Use the version 0.8.1 (the latest to the date) of the microservices-demo app
Fixes #1045, Fixes #1047, Fixes #1051, Fixes #1053, Fixes #1057

fix: Patch version 0.9 to address reported issues
