terraform/install.sh

The current install script assumes one billing account, and will have issues if there are multiple. This PR presents the user with a selection if more than one account is found
Uses similar logic as the project selector in the delete script https://github.com/GoogleCloudPlatform/stackdriver-sandbox/pull/4

Multi billing acct

---

src/loadgenerator/requirements.txt

Upgrade Jinja2 to version 2.10.1
* [CVE-2019-10906](https://nvd.nist.gov/vuln/detail/CVE-2019-10906)
* [GitHub Security Alert](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/network/alert/src/loadgenerator/requirements.txt/Jinja2/open)
Signed-off-by: Nathen Harvey <nathenharvey@google.com>

Address CVE-2019-10906 in loadgenerator

---

src/emailservice/requirements.txt

Upgrade Jinja2 to version 2.10.1
* [CVE-2019-10906](https://nvd.nist.gov/vuln/detail/CVE-2019-10906)
* [GitHub Security Alert](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/network/alert/src/emailservice/requirements.txt/Jinja2/open)
Signed-off-by: Nathen Harvey <nathenharvey@google.com>

Address CVE-2019-10906 in emailservice

---

terraform/install.sh

The backup variable in the installation script `IFS_bak` should be set prior to the change of value.

Don't set backup variable to new variable value.

---

.gitignore
terraform/03_gke_cluster.tf

Added "new" stackdriver monitoring and logging spec to gke cluster, rather than using the legacy feature.

added new stackdriver monitoring/logging to gke cluster

---

README.md
docs/index.html
src/frontend/templates/cart.html

- Added image parameter into Cloud Shell buttons so it opens up with ephemeral storage. This fixes #30 because every time you get a brand new clone of the code and brand new cluster.
- Fixed markdown lint issues
- Fixed typo in months

Updated Cloud Shell to use ephemeral storage and random fixes

---

kubernetes-manifests/adservice.yaml
kubernetes-manifests/checkoutservice.yaml
kubernetes-manifests/frontend.yaml
kubernetes-manifests/productcatalogservice.yaml
kubernetes-manifests/shippingservice.yaml
src/adservice/build.gradle
src/adservice/src/main/java/hipstershop/AdService.java
src/checkoutservice/Gopkg.lock
src/checkoutservice/main.go
src/frontend/Gopkg.lock
src/frontend/main.go
src/productcatalogservice/server.go
src/shippingservice/Gopkg.lock
src/shippingservice/main.go

Part of #133, subtask of #132  
Remove jaeger exporter from checkoutservice, shippingservice, frontend, and adservice because it isn't necessary to export to anything other than GCP and OpenCensus is being deprecated.

Remove opencensus jaeger exporter

---

CONTRIBUTING.md
Makefile

Our test clusters require the "https://www.googleapis.com/auth/cloud-platform" scope to talk with Trace and Profiler APIs. Add this scope to the Makefile and Contributing guide

Add scopes to cluster

---

tests/README.md
tests/monitoring_integration_test.py
tests/requirements.txt

#WHAT: Integration testing for Uptime Check, Alerting Policy, Notification Channel, and User Experience Dashboard
#WHY: We want to ensure the terraform provisioning actually produces the resources we want it to
#HOW: Utilizes pyunit to create a testing infrastructure to test the successful creation of the monitoring resources. Note that since monitoring resources are not automatically created, the testing cannot be automated yet either. So someone has to manually run the tests. Eventually we'd like to integrate this into the CI.
#TESTING: All tests pass.

Added integration tests for monitoring examples

---

terraform/install.sh

#WHAT: Update the version of terraform that's installed to be the latest version
#WHY: The current version is slightly too old and doesn't support the dashboard resource
#HOW: Changed which version of terraform we install.
#TESTING: install.sh script still works the same, terraform apply will now work in monitoring directory without manual reinstall of proper version.

upgrade terraform version

---

src/frontend/Dockerfile
src/frontend/Gopkg.lock
src/frontend/Gopkg.toml
src/frontend/main.go
src/frontend/middleware.go

Partially resolves #181, subtask of #132 
Progress so far:
(https://github.com/GoogleCloudPlatform/stackdriver-sandbox/pull/183#issuecomment-664690690).
TODO:
**How to test Metrics Manually:** Deploy (e.g. run `make deploy-continuous PROJECT_ID=<projectid>`) and observe what's printed to stdout from frontend service server. It'll look something like this, and obviously respond to requests to hipster shop.
<details><summary>Sample Output in Pretty JSON</summary>
<p>
```js
{
   "time":"2020-07-28T21:29:30.458881296Z",
   "updates":[
      {
         "name":"http_request_count{instrumentation.name=hipstershop/frontend}",
         "sum":5
      },
      {
         "name":"http.server.request_content_length{instrumentation.name=go.opentelemetry.io/otel/instrumentation/othttp,http.flavor=1.1,htt …
```

Telemetry frontend: metrics to stdout, tracing in http handlers, gRPC interceptor

---

terraform/03_gke_cluster.tf

fixes https://github.com/GoogleCloudPlatform/stackdriver-sandbox/issues/212
Change from 7xn1-standard-1 nodes to 4xn1-standard-2, to consume fewer IP resources

Changed node type to n1-standard-2

---

terraform/00_state.tf
terraform/02_project.tf
terraform/03_gke_cluster.tf
terraform/destroy.sh
terraform/install.sh
terraform/variables.tf

1. Implement the project creation process: create a project and a bucket and link the billing account.
2. Implement the project choosing process: let user to choose an existing project or create a new one.
3. Switch the Terraform backend from local to remote: Interpolate the bucket name in the backend config.
Update:
1. Add support to google.com account: projects should now be in /experimental-gke.
2. Change the way to get the billing ID: use a map to store (name:id) to avoid fuzzy search supported by the gcloud filter flag.
3. Remove code remarks and make code clean.
Update2:
1. Change the way to ensure bucket is created: put it in a retry loop.
2. Now it only fetches the projects under certain billing account.
3. Shows project creation time on the prompt.

Adding google.com accounts support and terraform stateful provisioning

---

terraform/monitoring/03_service_slo.tf
terraform/monitoring/04_alerting_policies.tf
tests/monitoring_integration_test.py

#WHAT: 1 availability and 1 latency SLO for the frontend and an alerting policy on error budget burn rate for each SLO.
#WHY: We want to have alerting policies on SLOs for each service since SLO setting and alerting on budget burn is part of good practice for monitoring
#HOW: Terraform resources for each custom service, SLO, and alerting policy.
#TESTING: Created tests for all created resources to ensure they are created. Content of each resource verified manually.
#Note: I'm a little iffy on the SLOs - if you notice they are set to 80% good/total because otherwise they will all fail and burn through their entire error budget. 80% does seem like a very low number to me for an SLO, but I do think the definition is correct.
Closes #70

frontend SLO and alerting policies

---

docs/index.html

- Remove the custom Cloud Shell image from the website until the ongoing issue is resolved
- remove the Cloud Shell editor pane (https://github.com/GoogleCloudPlatform/stackdriver-sandbox/issues/232)

Update Cloud Shell Button URL

---

.github/workflows/README.md
.github/workflows/ci.yml

To support end-to-end tests, we'll need to have different types of workers with different capabilities. Our current ci test is configured to run on any self-hosted worker. I have now created the `kind-cluster` label, and configured our current tests to only run on those workers

Label CI workers

---

docs/index.html

Re-inserts the custom Cloud Shell image to the website, now that the ongoing issue was resolved 
related: https://github.com/GoogleCloudPlatform/stackdriver-sandbox/pull/235

Use custom cloudshell image

---

.github/workflows/push-tags.yml
make-release.sh

In prep for tomorrow's release
fixes https://github.com/GoogleCloudPlatform/stackdriver-sandbox/issues/226
- make-release.sh will now update the website cloud shell button to reference the new cloud shell image tag
- our release automation will build and push new images for the cloud shell image

Integrate Cloud Shell in release process 

---

terraform/00_state.tf
terraform/02_project.tf
terraform/03_gke_cluster.tf
terraform/destroy.sh
terraform/install.sh
terraform/variables.tf

1. Add auth login when terraform init fails.
2. Add check on owner permission of a project.
3. Remove terraform warnings.
4. Adjust log wordings.

Add owner permission check and credential check

---

terraform/monitoring/00_provider.tf
terraform/monitoring/02_dashboards.tf
terraform/monitoring/variables.tf

We're running into an issue where Terraform seems to think there is no configured project for the monitored resource. This fix sets the project for the provider so that won't be an issue.
Not sure why the issue exists for some projects and not for others, this should fix it universally.
Also updating the types for the variables to suppress the warnings.
Closes #258

add project to monitoring terraform provider

---

terraform/03_gke_cluster.tf
terraform/install.sh
terraform/monitoring/02_dashboards.tf

1) Configures the user email for monitoring terraform
2) Gets rid of deprecated Zone for GKE cluster
3) Add back in the interpolation for the zone.
Closes #256 and #257

fix email and deprecations

---

terraform/monitoring/00_provider.tf

The interpolation was broken so this fixes it - will look to replace with non-deprecated version in the next release.

fix interpolation

---

terraform/install.sh

Added a loop to wait until gcloud is authenticated before continuing. The loop will wait for 5 minutes, and then give up
This is to get around an issue we're seeing with Google-internal accounts
Test using this link:
https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/Daniel-Sanche/stackdriver-sandbox.git&cloudshell_git_branch=fix-googler-auth&cloudshell_working_dir=terraform&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image:v0.1.14

Fix Googler authentication

---

terraform/install.sh

Re-auth the account so we have access to kubectl if we try to recreate a Sandbox in an existing tests.

gcloud auth

---

terraform/monitoring/00_provider.tf
terraform/monitoring/02_dashboards.tf

Since we're using a version > terraform 0.11.0 the interpolation syntax is deprecated and we can actually just directly call our functions/variables. 
Gets rid of warnings that the user would see.
Tested in Cloud Shell

get rid of interpolations for terraform

---

src/checkoutservice/Dockerfile
src/checkoutservice/Gopkg.lock
src/checkoutservice/Gopkg.toml
src/checkoutservice/main.go

Resolves #275 and subtask of #132. 
I decided to fix #276 too because otherwise it was introducing a lot of redundant code. Previously, we opened+closed a brand new connection every time we needed to call another service; checkout is a client to 6 services and a single ShipOrder has 10+ calls. I've changed it:
(1) Added the gRPC connections to the checkout service data structure
(2) Open the connections at the start, with OC and OT telemetry interceptors/handler wrappers. 
(3) Reuse the connections for subsequent calls (they're methods that belong to the checkout service and thus have access to the connections directly).
This happens to greatly simplify the code as well.
To test, deploy hipster shop, add things to your cart, and then check out. You should see the following trace with …

OpenTelemetry Tracing for Checkout Service + Reuse gRPC Connections

---

src/shippingservice/Dockerfile
src/shippingservice/Gopkg.lock
src/shippingservice/Gopkg.toml
src/shippingservice/main.go

Resolves #278, subtask of #132 
To test, deploy hipster shop and either (1) view your cart (which gives you a shipping quote) or (2) check out (which calls the shipping service to "ship" your items). You should see the following trace in your Cloud Trace console with `g.co/agent:opentelemetry`:

OpenTelemetry Tracing for Shipping Service

---

src/productcatalogservice/Dockerfile
src/productcatalogservice/Gopkg.lock
src/productcatalogservice/Gopkg.toml
src/productcatalogservice/server.go

Resolves #248 . Subtask of #132 .
To test, deploy the sandbox and you should see this in Cloud Trace (specifically, look for Span.{server, client}-hipstershop.ProductCatalogService/{ListProducts, GetProduct}):

OpenTelemetry Tracing for ProductCatalogService

---

.github/workflows/push-tags.yml

I've noticed the push-tags action sometimes tries to run when a new branch is pushed, instead of just on tag pushes. [Example](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/runs/956115563?check_suite_focus=true)
So far this hasn't been an issue, because the pipeline will fail when the tag doesn't match the expected format. To be safe though, this PR should make the Action ignore branches, and make the Action only trigger on real tag pushes

Improve tag actions

---

.github/workflows/push-master.yml

Fixes #227 
Instead of creating new Cloud Image only on tags, a Custom Cloud Shell Image is also created on updates to master.
Essentially, the only change here is that the code written to Push Cloud Shell Images to GCR in `push-tags.yml` is also added to `push-master.yml`.

Added logic to push-master.yml to create cloud image

---

.github/workflows/push-master.yml
.github/workflows/push-tags.yml

- It seems like a [PR that was merged recently](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/pull/289) broke the `push-master.yml` workflow. This fixes the issue
- The small [fix that I attempted ](https://github.com/GoogleCloudPlatform/stackdriver-sandbox/pull/288) for improving the `push-tags.yml` trigger didn't work as I expected. This tries a different way that seems to work for people [here](https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/21)

Fix GitHub Actions Issues

---

terraform/install.sh

Some users skip over the Monitoring Workspace creation because they aren't able to read the part in the script that asks them to create a monitoring workspace. 
Makes Workspace creation more visible to the user when running the install script and notifies them that there is something they need to do.
Hopefully this prevents users from accidentally skipping the Workspace creation.

emphasize workspace creation in install.sh

---

.github/workflows/push-master.yml

There was another bug in the GitHub Action for pushing Cloud Shell images on each commit to master. The workflow was trying to tag it with a non-existent version label, when we really want to tag with the git sha and latest

Fix GitHub Action Push Bug

---

.github/workflows/ci.yml

Fixes #215 
- Creates `docker build` command to `ci.yml` to build the image
- Specifies that if build does not work, it exits w/code 1
One down-side of adding this to CI is that building the image takes a long time. This is mainly due to the fact that it's being pulled from the Cloud Shell Base Image (a LARGE file). It took approximately 20 minutes for the CI pipeline to run within this PR.

Added test to CI to Build Custom Cloud Shell Image

---

terraform/02_project.tf
terraform/03_gke_cluster.tf

Changes data.google_project.project.id to data.google_project.project.project_id to prevent issues with setting the config through Terraform provider ~> 3.0.0

fix project_id in terraform

---

src/currencyservice/package-lock.json
src/currencyservice/package.json
src/emailservice/requirements.txt
src/paymentservice/package-lock.json
src/paymentservice/package.json
src/recommendationservice/requirements.txt

I've pinpointed these updates as causing the `PROJECT_ID not found` errors for 4 of the services. Reverting these commits makes them go away :)
One is pretty minor: `google-auth` from `v1.20.1` to `v1.20.0` for the python services. Hopefully this is not cause for concern.
The other is `@google-cloud/trace-agent` from `5.1.0` to`2.11.0` or `4.2.0` for the nodejs services. This is a more considerable change so we could work on finding a version in the middle that works for us.

Revert GCP dependencies updates that cause auth problems

---

terraform/02_project.tf

Enable sourcerepo api so that users won't need to enable it when uploading source repo during debugging.

enable sourcerepo api

---

src/checkoutservice/main.go
src/currencyservice/server.js
src/emailservice/email_server.py
src/frontend/main.go
src/paymentservice/tracer.js
src/productcatalogservice/server.go
src/recommendationservice/recommendation_server.py
src/shippingservice/main.go

Adds thorough and consistent documentation about the OpenTelemetry tracing instrumentation to each service. A few key points:
- How authentication is handled in the cloud trace exporters.
- Warnings for PROJECT_ID when the environment variable isn't found, but also noting that this is not needed when running on GCP.
- Reminders when certain implementations would not be appropriate for production environments (i.e. AlwaysSample)
- Distinguishing between "client" and "server" responsibilities within the services
- And other miscellaneous things!
Also, there was an OpenCensus tracer leftover in frontend - I removed it and tested to make sure it doesn't affect the dashboards.
Part of #132 - we're close to the end!

Documentation for OpenTelemetry Instrumentation

---

terraform/monitoring/03_service_slo.tf
terraform/monitoring/README.md
terraform/monitoring/dashboards/adservice_dashboard.json
terraform/monitoring/dashboards/frontend_dashboard.json
terraform/monitoring/dashboards/generic_dashboard.tmpl
terraform/monitoring/dashboards/recommendationservice_dashboard.json

Renames the cluster to cloud-ops-sandbox as a subtask of #334 
Needs to be merged after #337

rebranding for monitoring terraform

---

.github/workflows/e2e_scripts/clean.sh

As a result of #337 there is a small bug with cluster cleanup in the end to end test.
This resolves the issue.

fixed cluster name in e2e test

---

README.md

The root `README.md` file has been updated with the following changes:
- Adds custom cloud shell image URL to "Open in Cloud Shell" button
- "Open in Cloud Shell" button points at `v0.2.0` branch instead of `master`
- Updates instructions for running `install.sh` with custom cloud shell image
- "Stackdriver Sandbox" is re-branded to "Cloud Operations Sandbox" in some places; shortened to "Sandbox" in others
One potential issue this raises is that every time a new release occurs, not only will the "Open in Cloud Shell" button on the website have to be updated to point at `vx.x.x`, but the "Open in Cloud Shell" button in the root directory must be updated to point at new version as well, which could easily be missed.
Some potential solutions could be:
- redirecting users to website page …

Updated root documentation

---

terraform/install.sh
terraform/monitoring/03_services.tf
terraform/monitoring/04_slos.tf
terraform/monitoring/05_alerting_policies.tf
terraform/monitoring/variables.tf
tests/monitoring_integration_test.py

#WHAT: SLOs and alerting policies for 5 of the microservices using the automatically created Istio services.
#WHY: All services should have SLOs and alerting policies. Here we demonstrate how to use the Istio services for these monitoring examples.
#HOW: Terraform resources for each SLO and alerting policy
- Uses the Istio string for service identification that is automatically created by installing Istio
#TESTING: Tests added for all resources. Currently passing, will merge once tests go into CI.
Closes #71, #72, #73, #78, #79

istio service SLO and alerting policies

---

Makefile

As part of the rebranding, we update stackdriver-sandbox to cloud-ops-sandbox in cluster name

Update clustername for development

---

terraform/monitoring/02_dashboards.tf
terraform/monitoring/dashboards/cartservice_dashboard.json
terraform/monitoring/dashboards/checkoutservice_dashboard.json
terraform/monitoring/dashboards/currencyservice_dashboard.json
terraform/monitoring/dashboards/productcatalogservice_dashboard.json
tests/monitoring_integration_test.py

#WHAT: Dashboards for the cartservice, checkoutservice, currencyservice, and productcatalogservice. To make reviewing the dashboards easier here is a list of metrics that are in each service.
CartService:
k8 Memory Limit Utilization
k8 Memory Usage
Istio Client Request Count
Istio Server Request Count
OC gRPC OK calls
OC gRPC Errors
Istio Server Response Latencies
CheckoutService:
k8 CPU Limit Utilization
Istio Client Request Count
Istio Server Request Count
OC gRPC OK calls
OC gRPC Errors
Istio Server Response Latencies
CurrencyService:
k8 CPU Limit Utilization
Istio Server Request Count
OC gRPC OK calls
OC gRPC Errors
Istio Server Response Latencies
ProductCatalogService:
k8 Memory limit Utilization
Istio Server Request Count
OC gRPC OK calls
OC gRPC Errors
Istio Server Response …

Custom Dashboards for Remaining Services

---

.github/workflows/e2e_scripts/cleanup_monitoring.py
src/checkoutservice/main.go
terraform/monitoring/06_log_based_metric.tf
tests/monitoring_integration_test.py

#WHAT: Adds a log line in the CheckoutService that tracks which products are being ordered and then adds a count based log-based metric through Terraform. 
#WHY: Log based metrics is one of the GCP unique features - here we demonstrate how Terraform can be used to provision metrics and dashboards on the metric and a good example of a log-based metric. 
#HOW: Terraform resources for provisioning the metric and then a dashboard to show the metric.
#TESTING: Tests added to the integration test. 
Closes #80

Log based metric for checkout service

---

terraform/destroy.sh

https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/364
- Improves destroy.sh to show legacy `stackdriver-sandbox` projects
- also added some enhancements to make it work more like install.sh (only show owned projects, show creation date)

Find old projects in destroy.sh

---

terraform/install.sh

https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/367
Now waits for 5 minutes instead of 30 seconds

Increase Googler auth timeout

---

docs/README.md

Replaced Stackdriver with Cloud Operations and stackdriver-sandbox-xxx project or object names with cloud-ops-sandbox-xxx

Debranding stackdriver from user guide

---

README.md
docs/index.html
make-release.sh

The automated release script currently does not update the Open in Cloud Shell button on the README. This PR fixes that
I also updated the repo url on the README and website

Release updates readme

---

terraform/install.sh
terraform/monitoring/istio_service_setup.py

previously the indefinite wait would terminate early because of the condition on the while loop. This should fix it for the E2E test so that it properly waits forever for the services to appear.

bug fix for indefinite service wait

---

terraform/install.sh

1. Remove existing load generator when using old projects.
Fixes #378, #11.
2. Display cluster removal info in next step.
Fixes #32.

remove existing load generator when using old projects

---

cloud-shell/cloudbuild.yaml

Fixes issue in which images are being rebuilt but not being pushed to Google Container Registry. Both `latest` and `v0.2.0` images were being rebuilt, but `v0.2.0` images were not being pushed to GCR--this was an oversight on my part. I did not include `docker push` in the tagged image logic, which I unfortunately did not detect in the Build logs until this morning because I was looking to make sure the image was being built instead of pushed.
Necessary for Custom Cloud Shell Image certification of versioned images.
I tested the `cloudbuild.yaml` file using the manual Cloud Build trigger in GCP on this branch. The results can be found here: https://pantheon.corp.google.com/cloud-build/builds/08425f1d-854a-4842-b75e-00f64ee1e855?project=stackdriver-sandbox-230822.

Push tagged image

---

.github/workflows/README.md
.github/workflows/push-master.yml
.github/workflows/push-tags.yml
.github/workflows/update-custom-image.yml
cloud-shell/cloudbuild.yaml

Addresses https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/394
I realized the other day that our GitHub Actions are writing Cloud Shell images using cached base images, which effectively expire every week. I updated the Actions to use Elena's new Cloud Build trigger instead, which is more robust. I also added some improvements to the GitHub Action that kicks off the Cloud Build. Now, we can see the Cloud Build logs within the GitHub UI, and GitHub will mirror the Cloud Build completion status so we'll know if anything fails
Here's an example run:
https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/actions/runs/227498277

Fix Cloud Shell GitHub Actions

---

.github/workflows/ci.yml

We currently have a smoke test that pings the frontend >100 times, and if it sees a single error, it treats it as a failure. This has been flaky for us, often forcing us to re-run the entire CI test
I replaced the flaky smoke test with curl. It will do a simple ping against the home page and `/cart`, and ensures they both return 200. It also checks the homepage for the text `Hipster Shop`, ensuring we're returning meaningful content. This should cover the same error cases as the smoke test in a much simpler and more reliable way

Replace smoke test

---

terraform/install.sh

Sandbox creation using google.com accounts stopped working about a week ago due to policy changes.
In this change we are changing the procedure for Googlers: they will have all the Sandboxes created under `/untrusted/demos/cloud-ops-sandboxes` folder and request access via go/cloud-ops-sandbox-access
Fixes #392,#369
Testing: create a Sandbox from google.com account by following [this link](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/cloud-ops-sandbox.git&cloudshell_git_branch=FixGooglersSandboxCreation&cloudshell_working_dir=terraform&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image:v0.2.5)

Create googlers sandboxes in a new folder

---

docs/index.html
terraform/install.sh

~~I added a new warning for internal users that the Sandbox is currently working for Googler accounts. [Test link](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/Daniel-Sanche/stackdriver-sandbox.git&cloudshell_git_branch=googler-error-msg&cloudshell_working_dir=terraform&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image:v0.2.5)~~ (edit: Googler accounts are re-enabled)
I also added a warning pop-up to the website, warning users that it will take 15-20 mins to provision the project. That can be tested with
```
cd ./docs
python3 -m http.server 8081
```

Add website alert popup

---

terraform/loadgen/00_loadgen.tf

@nicklin37 alerted me that the latest run of the e2e tests shows that trying to provision a cluster in the `southamerica-east1-a` region failed. There's likely some setting that we need to manually toggle on but for now I think it's best to not try to use it.
exact error:
```
random_shuffle.zone: Creating...
random_shuffle.zone: Creation complete after 0s [id=-]
google_container_cluster.gke_loadgen: Creating...
null_resource.current_project (local-exec): Updated property [core/project].
null_resource.current_project: Creation complete after 1s [id=5712226751518038775]
Error: googleapi: Error 404: Not found: project "***" does not have an auto-mode subnetwork for network "default" in region "southamerica-east1"., notFound
on 00_loadgen.tf line 43, in resource "google_container_cluster" …
```

[loadgen] Remove southamerica-east-1 from regions, replace with us-west-1 regions

---

.github/workflows/e2e-latest.yml
.github/workflows/e2e-release.yml
.github/workflows/e2e_scripts/clean.sh
terraform/install.sh
terraform/loadgen/00_loadgen.tf
tests/provisioning/loadgen_test.py

Partially solves https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/444 by renaming the load generator to use a different name prefix
Also:
- add e2e tests so it doesn't happen again
- fixed the clean.sh for the e2e tests so that the load generator cluster is properly cleaned up between runs
- added 30 minute timeout to all e2e tasks in case it gets stuck

Fix reattaching to existing projects

---

terraform/install.sh

Fix for a minor issue that was bugging me: sometimes due to window size the workspace creation link would break over multiple lines, and then clicking the link would lead to the wrong GCP project and I'd get a 403. I'd have to resize my browser window and click again for it to work properly
This PR breaks the link out onto its own line to make this issue less likely

Add workspace link line break

---

make-release.sh
website/README.md
website/index.html

fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/455
- make-release.sh wasn't changing files in the new website directory. This fixes that automation
- manually updated index.html to point to v0.3.0 release
- removed the pop-up from the website to prevent potential pop-up blockers from breaking our deployment
- updated website README to use cloud operations branding

Fix website deployment

---

terraform/destroy.sh

- Fixed issue where destroy.sh script would only show you one option
[Open in Cloud Shell](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/Daniel-Sanche/stackdriver-sandbox.git&cloudshell_git_branch=fix-destroy-script&cloudshell_working_dir=terraform&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image:v0.3.0)

Fix destroy script

---

cloud-shell/Dockerfile
cloud-shell/cloudshell_open_cp.sh

- added sandboxctl to the path so we can now call it from anywhere in the custom cloud shell container.
- also added the terraform directory so we can call `install.sh` and `destroy.sh` from other directories (should we merge these into sandboxctl?)
- I added paths for both stackdriver-sandbox and cloud-ops-sandbox so Open in Cloud Shell buttons pointing at legacy forks still get this feature
[Open in Cloud Shell](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/cloud-ops-sandbox.git&cloudshell_git_branch=master&cloudshell_working_dir=terraform&shellonly=true&cloudshell_image=gcr.io/sanche-testing-project/cloud-shell:test3)

Add Sandboxctl to path

---

.github/workflows/e2e-release.yml
tests/provisioning/loadgen_test.py
tests/provisioning/provision_test.py
tests/provisioning/test_runner.py

fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/452
- fixed test-runner.py to exit 0 when tests fail
- fixed provisioning tests to pass (use implicit context instead of named one)
- moved "Test Using Existing Project" to bottom of the end-to-end release test, so it doesn't fail due to https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/453

Fix e2e provisioning tests

---

terraform/monitoring/06_log_based_metric.tf

Changes the alignment to show per day - results look like this: 
Closes #370

Log based metric fix

---

kubernetes-manifests/emailservice.yaml
kubernetes-manifests/recommendationservice.yaml
terraform/03_gke_cluster.tf
terraform/istio/install_istio.sh
terraform/istio/istio_operator.yaml

This PR patches #448 , and fully closes #371 and #372 . Also:
- Upgrades GKE to v1.15 -> v1.16 
- Upgrades Istio 1.5-1.7, which contained the `holdApplicationUntilProxyStarts: true` flag that fixes race condition
**Details**
The previous PR didn't handle Istio's role in the race condition, esp since InitContainer runs before Istio injection. So we occasionally still got DefaultCredentialsError. This PR fixes the race conditions in a less latent/hacky way.
The Full Race Condition:
1. `Initcontainer` within `AppContainer` starts and finishes
2. `Istio` starts.
3. [In parallel as 2] AppContainer starts. _AppContainer errors and crashes bc of missing certs. This is because Istio's envoy proxy isn't always ready yet._
4. Envoy finally gets cert configs & proxy is ready. _This delay is in part …

Patch #448: Better solves MDS/GoogleAuth/Istio race condition

---

README.md
cloud-shell/README.md
cloud-shell/cloudbuild.yaml
make-release.sh
website/index.html

We have an active issue where only the certified v0.2.0 image can be used for the existing cloud shell image path. This PR adds a new `gcr.io/stackdriver-sandbox-230822/cloudshell-image/uncertified` image path, and uses that for all GCR references in the repo for now
Long term, we should move the website to the certified image, and maintain both image paths

User uncertified images

---

sre-recipes/README.md
sre-recipes/recipe.py
sre-recipes/recipes/currencies_recipe/currencies_recipe.py
sre-recipes/sandboxctl

#WHAT: Refactors the sandboxctl CLI - moves the authentication and command running into the base class so it's usable by other recipes (since this will most likely be the case) and also uniforms naming across static and class methods. Also fixes some naming.
#WHY: Makes the CLI more portable for additional recipes

CLI refactor and hint method for sre recipes

---

src/emailservice/email_server.py
sre-recipes/recipe.py
sre-recipes/recipes/currencies_recipe/currencies_recipe.py
sre-recipes/recipes/encoding_recipe/__init__.py
sre-recipes/recipes/encoding_recipe/encoding_recipe.py
sre-recipes/sandboxctl

#WHAT: Another SRE recipe that introduces grpc errors into the email service by attempting to encode the email when the feature flag for encoding is set to true. 
#WHY: We want another example of SRE recipes for users to play with!
#HOW: used encoding as a sample "feature" to hide what the recipe really is - which is about sending errors in both logging that should also be shown in dashboards and SLOs.

SRE Recipe introducing errors into the email service

---

.github/workflows/e2e-latest.yml
.github/workflows/e2e_scripts/clean.sh
terraform/03_gke_cluster.tf

Improves on: #448
Changes: 
- Use default GCE service account for Workload Identity
- No longer creates a new Google service account for the GKE service account binding
- Fixes e2e test issue where we can't reapply to deleted service accounts
Note: While docs recommend we create new SAs for K8S clusters as a best practice, implementing it for Sandbox introduces unnecessary complexity to users. Agreeing with @Daniel-Sanche 's point that: "The only reason I'd hesitate is because we don't want to show bad patterns to our users, but I don't think workload identity is really in scope for what our customers would be looking at anyway."

E2e Fix: Use default GCE service account for Workload Identity

---

.github/workflows/e2e-latest.yml
renovate.json

Resolves #476 
**Changes:** 
- RenovateBot adds labels: `type: cleanup`, `priority: p1`, and `automerge`
- Reduces noise by rescheduling bot to run 1x week, after releases (see question1). 
- [Workflow Bot](https://github.com/nicoleczhu/workflow-controller) allows bots/whitelisted accounts to trigger CI.
**Open question:** 
1. Should we run RenovateBot 2x a week or on a different weekday? It's recommended we schedule [runs shortly after releases](https://docs.renovatebot.com/noise-reduction/#scheduling-renovate).
2. Should we let RenovateBot merge CI-passing PRs without owner approval?

Enable e2e latest on PRs with review requests & renovate bot configurations

---

.github/workflows/update-custom-image.yml
cloud-shell/cloudbuild.yaml
make-release.sh
website/index.html

We previously started using uncertified cloud shell images, when we discovered certified images force you to use a single version. Now that `cloudshell-image:latest` has been certified, we can go back to using that one on the website.
I updated the "rebuild cloudshell" action to keep the certified image up to date with the latest release. The uncertified images will continue to be built for each previous release, and I suggest we still use those for testing

Use certified image again

---

.github/config.yml

Main changes fyi: 
- Language labeling is turned off by default (until we add this config file)
- Can config languages based on project directory structure, e.g. /sr/emailservice -> "lang: python"
- Can config custom file extension to language mappings, e.g. "filename.ts" -> "lang: js"
- Can config label copy e.g. "language: python" instead of "lang: python" 
- I turned off labeling issues since it's hit and miss and will take a lot more work to get accurate.
- Config file is optional
A few things to discuss: 
1. How do we want to label repos like /terraform, /cloudshell. Or not label them? @Daniel-Sanche 
2. Do we want to label with as many languages as possible, or a whitelisted set of languages? I can add a `verbose` config to enable/disable this
3. Are you ok with the current set of …

Feat: customize how labeler bot detects languages with user config file

---

Makefile
terraform/03_gke_cluster.tf

I just checked today, issue #482 doesn't happen anymore with the GKE's [Oct 2 release](https://cloud.google.com/kubernetes-engine/docs/release-notes) where: "Version 1.16.13-gke.401 is the new default version for clusters with no & stable channels."

Fix: istio/gke version conflict by unpinning gke version

---

sre-recipes/sandboxctl

As part of our bugbash, we discovered an issue where `sandboxctl create` wouldn't show the output from `terraform apply`. This PR should fix that issue
[Click to Deploy](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/cloud-ops-sandbox.git&cloudshell_git_branch=fix-install&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image/uncertified:latest)

Fix sandboxctl create

---

README.md
make-release.sh

A couple small fixes before the release:
- the release script was using the wrong path for the load generator manifests
- the README didn't include the cloud shell tutorial, and was still using terraform as the working directory instead of the repo root

Fix release script and readme

---

loadgenerator-manifests/loadgenerator.yaml
src/loadgenerator/locust-tasks/basic_locustfile.py
sre-recipes/sandboxctl
terraform/install.sh
terraform/loadgen/00_loadgen.tf
tests/provisioning/loadgen_test.py

Fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/505
- We were seeing an exception thrown on the basic loadgenerator. This PR fixes that issue.
- I changed the loadgenerator from distributed to standalone mode to make it easier to deal with
- I changed the loadgenerator service to use the standard port 80 instead of 8089
- `sandboxctl loadgen` prints the loadgenrator web address after making changes
[Deploy in Cloud Shell](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/cloud-ops-sandbox.git&cloudshell_git_branch=fix-locust&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image/uncertified:v0.4.0&cloudshell_tutorial=docs/tutorial.md)

Fix locust

---

.github/workflows/e2e-latest.yml
renovate.json

Since we require a reviewer for all PRs, running e2e on branch:master, rather than review_requested, makes more sense. 
Also update renovatebot to request reviews from me weekly.

ci: run e2e on prs to master & set renovate reviewer to nicole

---

sre-recipes/recipe.py
sre-recipes/recipes/encoding_recipe/encoding_recipe.py
sre-recipes/sandboxctl

Removing sre recipe 1, as discussed in our meeting.
I added a new method to all recipes called `is_active()`. If overridden to return False in a subclass, that recipe won't appear in sandboxctl

Disable recipe1

---

terraform/03_gke_cluster.tf

@Daniel-Sanche here's a PR in case you want to remove the lagging zones for this release

build: remove zones a and c temporarily as they are behind latest gke release

---

.github/workflows/README.md
.github/workflows/e2e-latest.yml
.github/workflows/e2e-release.yml
.github/workflows/push-master.yml
.github/workflows/push-tags.yml

This lets us automatically run e2e workflows on PRs from RenovateBot
Btw: I looked into setting envvars globally (once across github actions) but it isn't easily done, like it is with setting envvars within workflow, job, or a step. It would require us to write the envvar to Github Actions' runtime disk using one of the workflows. Which feels messy/hard to read for contributors, so I opted to set envvars per each workflow. 
Let me know any feedback!

ci: moved project_IDs from secrets to env variable

---

renovate.json

- Suppresses wrongful PRs like #523. There is no protobuf:protoc v3.13.0. Latest version is 0.8
- removes "automerge" label from renovatebot, since we require 1 approving review for all PRs. Doing this because automerge label is verbose in the comments

chore: Ignore invalid package versions RenovateBot tries to update

---

.github/workflows/e2e-release.yml

The end-to-end tests targeting the latest release are failing. The issue is on the latest v0.4.0 release, we removed the `cloudshell_working_dir`argument, which is expected in the test scripts. This PR removes that variable so the tests will run again

fix: e2e release tests

---

terraform/monitoring/istio_service_setup.py

Fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/560
We were seeing an issue where it would hang on istio_service_setup, even though all the services were properly set up.
It looks like the issue was due to it interpreting the parameter to `get_service` as a GetServiceRequest object instead of a name string. This PR makes the parameter explicit to fix the issue

fixed parameter name

---

terraform/install.sh

Putting the creation of the Operations Workspace near the start of the script helps reduce the chance that the script or Cloud Shell times out waiting for a response from the user. Currently, the user may think the script is fully automated, put the Cloud Shell in the background, and then wind up with the script not completing. This lowers the chance of #543 happening and makes the documentation of it slightly cleaner.
I noticed the delay also helps reduce the number of times encountering #524. I encountered the issue 0 times (out of about 5) when testing this.

Put manual workspace creation near start of script

---

src/ratingservice/README.md
src/ratingservice/main.py
tests/ratingservice/main_test.py

add GET ratings/ method that returns _all_ ratings to call when showing frontend homepage.
add e2e test for the new API.
increase e2e test timeout to 5 seconds per API call.

Extend rating service API with GET ratings/ call to simplify integration with frontend

---

.github/workflows/ci.yml
src/frontend/handlers.go
src/frontend/main.go
src/frontend/rest.go
src/frontend/templates/home.html
src/frontend/templates/product.html

Setup HTML templates to have dynamic values of the rating.
Modify home page and product page handlers to populate product rating(s).
Add functionality to submit a new product rating.

integrate frontend service with rating service

---

docs/README.md
docs/tutorial.md

Added a brief description of what can happen and a button to relaunch the custom Cloud Shell container to the tutorial and the guide.

Instructions in tutorial and guide for re-launching custom Cloud Shell

---

.github/workflows/ci.yml
.gitignore
src/frontend/rest.go
terraform/monitoring/02_dashboards.tf
terraform/monitoring/04_slos.tf
terraform/monitoring/dashboards/ratingservice_dashboard.json
tests/monitoring_integration_test.py

Add a dashboard for monitoring service with the following metrics:
- responses by HTTP code
- 95th percentile of the response latency
- instance count by state
- throttled responses
Add availability (99% of non-4XX and 429 responses return 200) and latency (99% of 200 responses are returned within 150ms) SLOs for 30 window.
Refactor .gitignore to ignore terraform files under /terraform/monitoring.
Some formatting was committed due to use of VSCode for editing.

add rating service monitoring metrics

---

sre-recipes/sandboxctl
terraform/05_loadgen.tf
terraform/install.sh
terraform/variables.tf

This PR adds a `--skip-loadgenerator` flag to deploy without the loadgen cluster. As part of the change, I also enabled `sandboxctl create` to send arguments to `install.sh`, and documented these arguments at `sandboxctl create --help`. (Previously, install.sh accepted some arguments, but you couldn't use them in sandboxctl)
[Open in Cloud Shell](https://console.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/cloud-ops-sandbox.git&cloudshell_git_branch=optional-loadgen&shellonly=true&cloudshell_image=gcr.io/stackdriver-sandbox-230822/cloudshell-image/uncertified:v0.4.0)

feat: make loadgenerator optional

---

src/emailservice/email_server.py

fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/607
The service was trying to run `.lower()` on an unset env var, resulting in spammy logs. I added a default value of false to the field to fix this

add default value for emailservice env var

---

terraform/install.sh

fix: #601 
Run load generator for ~10-15s during installation. 
Adds ~5s to previous install time. 
**Load specs:** 
user_count=50
spawn_rate=10
At the end of 5 seconds we delete users that have already been created. 
**Note:** 
There's a race condition where `curl http://loadgen_ip/stop` to stop loadgen returns a successful http response (and UI indicates the swarm has terminated..) 
BUT this only terminates users that have already been spawned, not the users that were originally scheduled to spawn! [Bug filed with Locust here](https://github.com/locustio/locust/issues/1661). 
For us this might be nice as sandbox users will continue to get traces/metrics from any undeleted remaining users from Locust.
**Context:** 
We wanted to provide initial traffic telemetry for users to view && still …

feat: run loadgen for a few seconds during installation

---

.github/workflows/update-custom-image.yml
cloud-shell/cloudbuild.yaml

Our Cloud Build images are failing to build due to the default 10 minute time out. This bumps the number to 30 mins
I won't merge this until this action completes to be sure it works:
https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/runs/1786250435?check_suite_focus=true

fix: cloud build timeout issue

---

cloud-shell/cloudbuild.yaml

We're still seeing issues with the cloud build trigger. It looks like a config-level timeout needed to be added in addition to the step-level one.
This change was able succeed in the automated pipeline: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/actions/runs/518912854

fix: add config-level timeout

---

src/cartservice/Dockerfile

The cartservice is failing to build due to an expired certificate in the base image. This applies the same fix that was submitted to the hipstershop upstream repo: https://github.com/GoogleCloudPlatform/microservices-demo/pull/496

fix: change cartservice base image

---

src/ratingservice/main.py
sre-recipes/recipe.py
sre-recipes/recipes/ratings_freshness_recipe/__init__.py
sre-recipes/recipes/ratings_freshness_recipe/ratings_freshness_recipe.py
terraform/monitoring/04_slos.tf
terraform/monitoring/06_log_based_metric.tf
terraform/ratingservice/app.yaml.tpl
terraform/ratingservice/main.tf

A new recipe 'rating_freshness' is added that should cover data freshness SLO of the rating service.
To support the recipe a new (3rd) SLO is define for the rating service. This is 1 day rollowing window SLO that defines a good time as a 1 minute interval during which there were at least 1 successful call to recollect API.
The SLO uses log-based metric which counts number of calls to recollect API.

Add SRE recipe for rating service

---

README.md

Change the link to search for monitoring as current link is broken and there is no monitoring category in the codelabs anymore.
There is cloud event/folder in the codelabs site but it seems not searchable so cannot limit search result to GCP.

[docs] update codelab link

---

src/recommendationservice/requirements.txt

fixes security vulnerability: https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/security/dependabot/src/recommendationservice/requirements.txt/PyYAML/open

fix: update pyyaml dependency

---

src/emailservice/email_server.py
src/emailservice/requirements.in
src/emailservice/requirements.txt
src/recommendationservice/recommendation_server.py

Re-enables the GCP debugger for emailservice. It was taken out previously due to the old package breaking
Also modified how the debugger is enabled in the recomendation service so both services are consistent
Fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/325

fix: add gcp debugger to email service

---

terraform/install.sh

There is no need anymore for setupOperationsWorkspace step as there is a default workspace now in SD.
Verified against master in current version, release is now GA so should support customers as well.

Remove msg about creating Workspace in Cloud Operations   

---

website/content/en/docs/getting_started.md

Update the target version in the launch URL for "Open in Cloud Shell" button.

nit: Fix the target version to launch in getting started doc

---

sre-recipes/recipe.py
sre-recipes/sandboxctl
terraform/destroy.sh

Added run_command_interactive to solve sandboxctl destroy hang without affecting other call to run_command function.

Fix sandboxctl destroy timeout

---

src/cartservice/Startup.cs
src/cartservice/cartservice.csproj
src/cartservice/cartstore/RedisCartStore.cs

This automatically adds trace information for the call from the cartservice to Redis and puts it in the context of the existing call from the frontend to the cartservice.
The service call is essentially just a wrapper around the Redis call, so they are basically the same in this case, but this is still a useful example of using OpenTelemetry to instrument a third-party library for trace.

Add Redis Trace instrumentation to cartservice

---

terraform/loadgen/00_loadgen.tf
tests/provisioning/loadgen_test.py

This Loadgen machine type was missed in previous merges.
"n1-standard-1" is what was tested and documented as part of cost estimation optimization and documentation.

Fix loadgen machine type

---

.github/workflows/e2e-latest.yml
.github/workflows/e2e-release.yml
.github/workflows/e2e_scripts/run_install.sh
sre-recipes/sandboxctl
terraform/install.sh

We previously had the `--skip-workspace-prompt` to allow our automation to work without interaction. Now that the workspace set-up requirement is gone, we can remove the argument

remove sandboxctl "skip-workspace-prompt" argument

---

CONTRIBUTING.md
website/deploy/index.html
website/layouts/index.html

This PR adds integration with Google Feedback (listnr):
On the main page it will feature a button that will trigger taking a screenshot and sending a report with feedback to Google.
Fixes #725 
(I can't upload a picture from my machine but it looks like this:
[ Submit Feedback ]
And the button is placed on the bottom footer of the landing page.
I tried to test it but it looks like we need to allow-list the domain from which the call is made. So in testing nothing happens on the page. When this code is deployed to cloud-ops-sandbox.dev, it should, upon click, open a screenshot dialog, similar to feedback dialog on cloud.google.com pages.

feat: Add Google Feedback to Sandbox main page

---

.github/workflows/README.md
.github/workflows/check-tags.yml
.github/workflows/gitflow-enforcer.yml

Added two new GitHub Actions:
- gitflow-enforcer blocks non-release PRs to main, and adds a comment pointing to the contributing guide
- check-tags ensures that develop and main both maintain proper tagging policies (develop should pin to latest, main should pin to a version)
gitflow-enforcer enforcer is expected to fail for this PR, but we **actually do** want to merge this last one directly to main, to make sure it is protected going forward

ci: add new gitflow enforcer actions

---

.github/workflows/update-custom-image.yml
cloud-shell/Dockerfile
cloud-shell/cloudbuild.yaml

The cloud build container workflow is currently broken. This PR:
- increases timeout
- builds only the 3 latest tags (to save compute time)
- pins python dependency versions in the cloud shell container
- always uses the develop branch as the base

ci: fix cloud build container workflow

---

sre-recipes/sandboxctl

Fix outdated sandboxctl command for `loadgen`.
This should fix a potential crash loop in loadgen, but the crash loop in frontend server in issue #791 is unrelated to loadgen. 
It seems to related to availabilities itself.

fix: update outdated loadgen env variable in sandboxctl

---

cloud-shell/cloudshell_open_cp.sh
terraform/telemetry.py

- Telemetry isn't being sent on develop due to a regex check. We now want to accept "develop" as a valid version field
- Telemetry isn't being set on `main` due to the version environment variable not being found. It looks like recent versions of the cloud shell container stopped sourcing `/etc/environment`. This PR adds this back to the cloud shell run steps

fix: telemetry on develop branch

---

.github/workflows/README.md
.github/workflows/develop-website.yml
.github/workflows/manual-website.yml
.github/workflows/prod-website.yml

There was a bug in the GitHub Actions workflow that was meant to update the staging website.  It wasn't setting the AppEngine service name, so it would fall back to `default`. 
This PR fixes the bug, and separates the `develop` and `manual staging` Actions to simplify the logic and make it easier to catch similar bugs in the future

fix: website update workflows

---

kubernetes-manifests/adservice.yaml
kubernetes-manifests/cartservice.yaml
kubernetes-manifests/checkoutservice.yaml
kubernetes-manifests/currencyservice.yaml
kubernetes-manifests/emailservice.yaml
kubernetes-manifests/frontend.yaml
kubernetes-manifests/paymentservice.yaml
kubernetes-manifests/productcatalogservice.yaml
kubernetes-manifests/recommendationservice.yaml
kubernetes-manifests/shippingservice.yaml
tests/recipes/test_recommendation_crash_recipe.sh

fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/815
The Cloud Logging dashboard adds the container name beside the log for better readability. Except most of our services use the name "server" for the container, which isn't helpful for debugging.
This PR will give each service a unique name

feat: renamed k8s containers to display service names

---

.github/workflows/ci.yml
.github/workflows/e2e-latest.yml
sre-recipes/README.md
sre-recipes/recipes/configs_based/README.md
sre-recipes/recipes/configs_based/recipe2.yaml
sre-recipes/recipes/configs_based/schema/README.md
sre-recipes/recipes/configs_based/schema/defs/README.md
sre-recipes/recipes/configs_based/schema/defs/action-config-list.schema.json
sre-recipes/recipes/configs_based/schema/defs/loadgen-spawn.schema.json
sre-recipes/recipes/configs_based/schema/defs/loadgen-stop.schema.json
sre-recipes/recipes/configs_based/schema/defs/multiple-choice-quiz.schema.json
sre-recipes/recipes/configs_based/schema/defs/run-shell-commands.schema.json
sre-recipes/recipes/configs_based/schema/schema.json
sre-recipes/requirements.txt
tests/recipes/validate_recipe_configs.py
tests/requirements.txt

The validation mainly relies on the newest JSON Schema (https://json-schema.org) definition, and it works by first converting the YAML config to JSON, and then validate directly on the converted JSON. Added relevant README changes as well.
In order to make decoupling JSON schema easier, I decided to write a custom schema bundling logic for schema "references", since the Python version of the JSON schema validator doesn't support referencing local files well.

tests: Add integration tests for validating SRE Recipe config schema

---

terraform/01_provider.tf

we're seeing sandbox failures now that the google-beta provider updated to v4.x. This PR pins it to the last known working version (v3.90.0), rather than accepting arbitrary updates

fix: pin terraform providers to specific version

---

terraform/03_gke_cluster.tf

Update deprecated workload_identity_config and workload_metadata_config

fix(terraform): update deprecated GKE params

---

src/currencyservice/Dockerfile
src/paymentservice/Dockerfile
src/ratingservice/requirements.txt

The rating service recently started to break deployment, due to a new dependency issue. This PR pins pyparsing, which should fix the issue
Fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/877

fix: rating service dependencies

---

src/adservice/build.gradle

upgrade log4j2 package to 2.15.0 to fix ZD CVE-2021-44228

fix: CVE-2021-44228

---

src/adservice/build.gradle

Updates log4j to version 2.16
Fixes https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/889

fix: CVE-2021-45046

---

.github/workflows/make-release.yml
.github/workflows/pr-comment-bot.yml
CONTRIBUTING.md
README.md
website/content/en/docs/getting_started.md
website/deploy/docs/_print/index.html
website/deploy/docs/getting_started/index.html
website/deploy/index.html
website/layouts/index.html

The cloud shell team changed their URL format to start with "shell" instead of "console". The old format is meant to still work, but there were some issues this week on their backend, so we should change over to the new format to be safe

chore: update "open in cloud shell links" to use new format

---

cloud-shell/Dockerfile
tests/monitoring_integration_test.py

kubectl authentication is changing in the latest gcloud builds. We need to install an extension in the custom cloud shell image to be able to reliably authenticate to our GKE clusters

chore: install kubectl extension

---

terraform/get_terraform_vars.sh

Sandbox deployments are currently failing due to unexpected output from the get_terraform_vars script.
It looks like gcloud was updated to be more verbose, writing extra text to stdout. Terraform expects this script to only print a JSON object, so I re-directed the output from gcloud commands

fix: get_terraform_vars extra stdout output

---

.github/auto-label.yaml

Replaces https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/pull/922
Enable staleness and pull request size bots on the repo

fix: Enable staleness and pull request size bots on the repo 

---

terraform/monitoring/03_services.tf
terraform/monitoring/04_slos.tf
terraform/monitoring/05_alerting_policies.tf

- Previously, terraform was setting up duplicate dashboards; some created by istio, and some created manually. This PR removes the custom ones, so the Cloud Monitoring interface is easier to read
- I also loosened some of the SLO definitions. Currently they would instantly fail and send out alerts. We would prefer a fresh sandbox to be within its SLO budget

feat: simplify service dashboards

---

terraform/03_gke_cluster.tf

Over the last few weeks, we've been seeing missing data in the Cloud Ops products on new sandboxes. I thought this was due to our outdated version of Istio, but after some experimentation, it looks like it was due to incorrect permissions on the GKE cluster service account
This PR fixes the issue by adding extra roles to the default compute instance service account, ensuring GCP observability client libraries can send data to Cloud Ops

fix: Cloud Ops permission errors

---

terraform/ratingservice/01_project.tf
terraform/ratingservice/04_appengine.tf

Enable the Cloud SQL Admin API and add Cloud SQL Client role for the
App Engine service account. 
See https://cloud.google.com/sql/docs/mysql/connect-app-engine-standard for more background.

fix: Enable the cloud-sql-proxy path to Cloud SQL for ratingservice

---

.github/workflows/make-release.yml
.github/workflows/update-custom-image.yml
tests/run_tests.sh

- We recently added `sandboxctl test` to run tests against a live sandbox environment, but it wasn't working for the ratingservice tests. This fixes that
- added a dependency to the make-release release pipeline, so it will run steps in sequence instead of parallel (https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues/943)
- removed quotes from workflow custom image trigger, since the trigger wasn't firing and removing quotes seems to be better in line with the spec

chore: test adjustments

---

docs/tutorial.md

removes `$` symbol from beginning of the code blocks to
allow copy/paste commands into shell
Fixes #882

docs: removes `$` from shell commands

---

terraform/02_project.tf
versions.json

Saves Sandbox installed version and app-id into the Google Cloud project's metadata.
Enables compute API in order to operate the project's metadata.
Fixes #982

feat: preserve sandbox metadata in gcp project metadata

---

kubernetes-manifests/cartservice.yaml

Pin the version of busybox image in init-redis-ready container of the cartservice
to the version 1.28 that does not have a problem with nslookup
Fixes #995

fix: resolve cartservice initialization

---

docs/walkthrough.md
provisioning/sandboxctl
provisioning/terraform/providers.tf

Fixes for version 0.9.2 including
- Show error message when CLI commands fail due to terraform error (🛠️ Fixes #1041)
- Support Terraform versions 1.5.* (🛠️ Fixes #1040)
- Update walkthrough to correct instruction in command (🛠️ Fixes #1039) and add missing instruction for application authentication for Terraform (🛠️ Fixes #1041)

fix: Add support for Terraform 1.5 and fix issues in CLI and walkthrough doc

---

README.md
docs/README.md
provisioning/sandboxctl

Replace `loging` with `login` in the tutorial and README(s).
Use correct variable (`SANDBOX_VERSION` instead of undefined `VERSION`) to print version in `sandboxctl -version` CLI.
Add missing `create` command in README docs.
🛠️ Fixes #1047, Fixes #1045

fix: fix incorrect instructions and CLI
